name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Docker meta
      id: docker_meta
      uses: antoniodelfim/ghaction-docker-meta@v1
      with:
          images: ghcr.io/webapp/webapp
          tag-sha: true
          tag-edge: false
          tag-latest: true
          
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Login to GHCR
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
   
    - name: Push image
      uses: docker/build-push-action@v2
      with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          file: ./Dockerfile
      
